services:
  pgsql_db:
    image: postgres:16.4
    container_name: pgsql_db
    hostname: pgsql_db
    ports:
      - '5433:5432'
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: testdb
    volumes:
      - db_vol:/var/lib/postgresql/data

volumes:
  db_vol:
